name: Lint + Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      # Run package build+ lint + tests
      - run: npm install
      - run: npm run lint
      - run: npm run fmt:check
  test:
    name: Run jest tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci
        
      - name: Jest
        run: npm test -- src/wallet_client.test.ts
